spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  data:
    mongodb:
      host: localhost
      database: mongo
      username: mongo
      password: mongo
      port: 27017
      authentication-database: admin
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.yml

logging:
  level:
    org.springframework.security: DEBUG