spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/secureskye
    username: postgres
    password: postgres
  data:
    mongodb:
      host: localhost
      database: mycollection
      username: mongodb
      password: mongodb
      port: 27017
      authentication-database: admin
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.yml

#logging
logging:
  level:
    org.springframework.data: debug
    .: error